// Sound-design cues. Each cue is tied to a visual event through an anchor word, so it moves with the voice.
// Guidelines: one soft procedural family of sounds (e.g. generated by a synth script into public/audio/sfx/<name>.wav),
// 20–30 dB under the voice, at most ~2 "hits" in the whole film, nothing on the end card. A cue whose .wav file is
// missing is skipped, so the list can be written before the sounds exist.
//
// Example:
//   { scene: "s_example", at: "result", offset: 0, sfx: "pop", vol: 0.06 }          // on the anchor word "result"
//   { scene: "s_example", at: 45, sfx: "tick1", vol: 0.05 }                          // 45 frames into the scene
//   { scene: "s_example", at: "line:c", offset: 6, sfx: "hit", vol: 0.1 }            // just after line c starts (a reveal tied
//                                                                                    // to a sentence, not a word: same in every language)
//   { scene: "s_example", at: "chart", sfx: "whoosh", vol: 0.08, cut: "en" }         // only in the EN voice cut
//   WHOOSH_INTO = ["s_results"]  -> a whoosh peaking on the cut into that scene
//   MUSIC_DROPOUTS = [["s_results", "result", 18, 2]] -> the music dips from 18 frames before to 2 after that word
import type { Timeline } from "./timeline";

export type SfxName = "whoosh" | "pop" | "tick1" | "tick2" | "tick3" | "hit" | "stamp" | "shimmer" | "powerdown";
export type Cue = {
  scene: string; // scene id
  at: string | number; // anchor name, "line:<id>" (that line's first word), or a frame number relative to the scene start
  offset?: number; // frames added to the resolved position
  sfx: SfxName; // file: public/audio/sfx/<sfx>.wav
  vol: number; // linear volume, typically 0.04–0.14
  cut?: string; // only in this voice cut (anchors differ per language)
};

export const CUES: Cue[] = [];

/** Scene ids whose incoming cut gets a whoosh (the whoosh is placed WHOOSH_PEAK frames before the cut). */
export const WHOOSH_INTO: string[] = [];
const WHOOSH_PEAK = 8;
const WHOOSH_VOL = 0.09;

/** Music drop-outs right before a headline claim: [scene id, anchor, frames before, frames after]. */
export const MUSIC_DROPOUTS: [string, string, number, number][] = [];

export type ResolvedCue = { frame: number; sfx: SfxName; vol: number; key: string };

export const resolveCues = (tl: Timeline, cut: string): ResolvedCue[] => {
  const out: ResolvedCue[] = [];
  const anchorOf = (sceneId: string, at: string | number) => {
    const s = tl.scenes.find((x) => x.id === sceneId);
    if (!s) return null;
    if (typeof at === "number") return s.from + at;
    if (at.startsWith("line:")) {
      const l = s.lines.find((x) => x.id === at.slice(5));
      return l ? s.from + l.from : null;
    }
    for (const l of s.lines) if (at in l.anchors) return s.from + l.anchors[at];
    return null;
  };
  WHOOSH_INTO.forEach((id) => {
    const s = tl.scenes.find((x) => x.id === id);
    if (s) out.push({ frame: Math.max(0, s.from - WHOOSH_PEAK), sfx: "whoosh", vol: WHOOSH_VOL, key: `wh-${id}` });
  });
  CUES.forEach((c, i) => {
    if (c.cut && c.cut !== cut) return;
    const fr = anchorOf(c.scene, c.at);
    if (fr !== null) out.push({ frame: Math.max(0, fr + (c.offset ?? 0)), sfx: c.sfx, vol: c.vol, key: `c${i}` });
  });
  return out.sort((a, b) => a.frame - b.frame);
};
